services:
  api:
    depends_on:
      - postgres
    build:
      context: ./
      target: backend-dev
    develop:
      watch:
        - path: ./
          action: sync
          ignore:
            - ./node_modules/
            - ./package.json
            - ./.env
            - ./.env.test
          target: /usr/local/app/src
        - path: ./package.json
          action: rebuild
        - path: ./.env
          action: rebuild
        - path: ./.env.test
          action: rebuild
    ports:
      - 3000:3000

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: drop4@b23!
      POSTGRES_PASSWORD: klazX.@345
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
