version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:24.13.0
      - image: cimg/postgres:17.0
        environment:
          POSTGRES_USER: ${POSTGRES_TEST_USER}
          POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
          POSTGRES_DB: ${POSTGRES_TEST_DB}

    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: $POSTGRES_TEST_USER
      DATABASE_PASSWORD: $POSTGRES_TEST_PASSWORD
      DATABASE: $POSTGRES_TEST_DB
      DATABASE_SYNCRONIZE: 'false'
      DATABASE_RUN_SEEDS: 'true'

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

      - run:
          name: Verify env resolution
          command: |
            echo "DB USER=$DATABASE_USERNAME"
            echo "PG USER=$POSTGRES_TEST_USER"

      # Wait for Postgres to be ready
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m


      - run:
          name: Run E2E tests
          command: npm run test:e2e -- --coverage

      - run:
          name: Build app
          command: npm run build

      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
