version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:24.13.0
      - image: cimg/postgres:17.0

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

      # Wait for Postgres to be ready
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run E2E tests
          command: npm run test:e2e -- --coverage

      - run:
          name: Build app
          command: npm run build

      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test:
          context: test
